export default function getTilesBackgrounds() {
  const names = [
    'starter',
    // 'straightSmall',
    // 'straightMedium',
    // 'straightBig',
    // 'elongatedCross',
    // 'skewedCross',
    // 'regularCross',
    // 'smallCross',
    // 'zee',
    // 'smallZee1',
    // 'smallZee2',
    // 'skewedZee',
    // 'regularCrossHhalf',
    // 'smallCrossHalf',
    // 'bigTee',
    // 'smallTee',
    // 'elBig',
    // 'elMedium1',
    // 'elMedium2',
    // 'elSmall1',
    // 'elSmall2',
    // 'square',
    // 'squareAppendix',
    'squareAppendixLong',
    'squareAppendixLong1',
    'squareAppendixLong2',
    'squareAppendixLong3',
    'squareAppendixLong4',
    'squareAppendixLong5',
    'squareAppendixLong6',
    'squareAppendixLong7',
    'squareAppendixLong8',
    'squareAppendixLong9',
    'squareAppendixLong10',
    'squareAppendixLong11',
    'squareAppendixLong12',
    'squareAppendixLong13',
    'squareAppendixLong14',
    'squareAppendixLong15',
    'squareAppendixLong16',
    'squareAppendixLong17',
    'squareAppendixLong18',
    'squareAppendixLong19',
    'squareAppendixLong20',
    'squareAppendixLong21',
    'squareAppendixLong22',
    'squareAppendixLong23',
    'squareAppendixLong24',
    'squareAppendixLong25',
    // 'squareAppendixCurved',
    // 'rectangleAppendixes',
    // 'hat',
    // 'zeeFat',
    // 'ceeSmall',
    // 'ceeBig',
    // 'hehe',
    // 'tetris',
    // 'spaceBattleship',
  ];

  const backgrounds = Array.from({ length: 42 }, (_, i) => i + 1);

  for (let i = backgrounds.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [backgrounds[i], backgrounds[j]] = [backgrounds[j], backgrounds[i]];
  }

  return Object.fromEntries(names.map((name, index) => [name, backgrounds[index]]));
}
