name: Build and publish to github packages

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


    - name: Build and publish image
      uses: uraimo/run-on-arch-action@v2
      with: 
        arch: aarch64
        distro: archarm_latest
        install: |
          pacman -Syu --noconfirm
          pacman -S docker docker-compose --noconfirm
        run: |
          docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker compose build
          docker compose push

    - name: Call frontend image webhook
      run: curl ${{ secrets.FRONT_AZURE_WEBHOOK }} -H "" -d ""

    - name: Call backend image webhook
      run: curl ${{ secrets.BACK_AZURE_WEBHOOK }} -H "" -d ""
